21 customer module
cybergroupdevs/uv-python-poc pull request #22
Opened 2020-06-05 18:45 UTC by ashishrawat0

Customer component and its service added

2020-06-10 02:35 UTC, KartikyaThakur requested changes

2020-06-10 02:35 UTC, KartikyaThakur commented on frontend/uv-poc/src/app/customer-details/customer-details.component.ts
> +import { CommissionService } from "../service/commission.service";
These still use `"` while all other files use `'`

2020-06-10 02:35 UTC, KartikyaThakur commented on frontend/uv-poc/src/app/customer-details/customer-details.component.ts
> +          this.customerDetails = Object.values(res[0]);
Why is `res` an array if it is going to be a single value?

2020-06-10 02:35 UTC, KartikyaThakur commented on frontend/uv-poc/src/app/customer-details/customer-details.component.ts
> +          this.customerDetails = Object.values(res[0]);
Why are we taking only the value instead of utilizing the JSON itself?

2020-06-10 02:35 UTC, KartikyaThakur commented on frontend/uv-poc/src/app/customer-details/customer-details.component.html
> +  </div>
Bad design, never rely on sequence of data when you can leverage object keys.

2020-06-11 22:35 UTC, KartikyaThakur commented on frontend/uv-poc/src/app/customer-details/customer-details.component.ts
> +          this.customerKeys = Object.keys(this.customerData);
Instead of going through all this, wouldn't it be better to just have the headers in the HTML itself?

2020-06-12 04:30 UTC, ashishrawat0 commented on frontend/uv-poc/src/app/customer-details/customer-details.component.ts
> +          this.customerKeys = Object.keys(this.customerData);
@KartikyaThakur  Okay, but you said if someone adds a new key that will create a problem but in this method, it would automatically show the new data. But I will now use HTML headers instead. if I am not wrong it will replace the ngfor and set the data individually

2020-06-12 04:48 UTC, ashishrawat0 commented on frontend/uv-poc/src/app/customer-details/customer-details.component.ts
> +          this.customerKeys = Object.keys(this.customerData);
@KartikyaThakur Instead of giving individual heading now I am going to add only those keys which are available to customerData if someone adds extra data to JSON then change will be required only at customerDetails.ts

2020-06-15 02:06 UTC, KartikyaThakur approved these changes

2020-06-15 02:07 UTC, merged