24 transaction component
cybergroupdevs/uv-python-poc pull request #33
Opened 2020-06-08 13:54 UTC by lakshyakalia

2020-06-11 22:39 UTC, KartikyaThakur requested changes

2020-06-11 22:39 UTC, KartikyaThakur commented on frontend/uv-poc/src/app/transaction-detail/transaction-detail.component.ts
> +    this.postedOn = details.customerDetails['date'];
What is the benefit of setting individual values instead of just using or assigning the entire object `details.customerDetails` itself?

2020-06-11 22:39 UTC, KartikyaThakur commented on frontend/uv-poc/src/app/home/home.component.html
> +        <p>this is just a proof of concept, don't save production data</p>
`don't save production data`  isn't a valid statement for this application as it only reads data, doesn't write anything.

2020-06-12 08:49 UTC, lakshyakalia commented on frontend/uv-poc/src/app/home/home.component.html
> +        <p>this is just a proof of concept, don't save production data</p>
This is just a sample data. We can discuss this once we discuss how the wireframes should look like.

2020-06-12 10:03 UTC, lakshyakalia commented on frontend/uv-poc/src/app/transaction-detail/transaction-detail.component.ts
> +    this.postedOn = details.customerDetails['date'];
Done

2020-06-15 02:10 UTC, KartikyaThakur approved these changes

2020-06-15 02:11 UTC, merged