changes in unit-test file and few changes in backend file
cybergroupdevs/uv-python-poc pull request #6
Opened 2020-05-27 02:46 UTC by ashishrawat0

2020-05-29 02:00 UTC, KartikyaThakur requested changes

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/unit-test.py
> +    def test_get_customerHistory(self):
Kindly stick to these [naming conventions](https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html).

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/unit-test.py
> +    def test_get_customerHistory_noHistory(self):
Kindly stick to these [naming conventions](https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html).

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/unit-test.py
> +    def test_get_consultant_businessName(self):
Kindly stick to these [naming conventions](https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html).

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/unit-test.py
> +    def consultant_businessName(self):
Kindly stick to these [naming conventions](https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html).

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/unit-test.py
> +    def customer_history_noHistory(self):
Kindly stick to these [naming conventions](https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html).

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
> +		details["pf"]="pf"
Why is `details` a better name than `customer`?

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
> +		data.append(customer_id+" Not found")
- `N` should be lowercase since it won't be the first word in the sentence
- Prefer using f-string instead of concatenation with the `+` operator

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
> +		data.append(customer_id+" Not found")
If the API is supposed to return JSON on success, then why are we returning just a raw string on error?

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
> +	if(check_key('CommEmplType',transaction_details['TRANSACTION'][0]["ITEM_MV"][0])==True):
Please give a few minutes to read the answer by Tim Goodman for [this question](https://softwareengineering.stackexchange.com/questions/12807/make-a-big-deal-out-of-true).

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
> +		status=200,
What value does the extra space provide here?

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
> +	if(check_key("FITTER",transaction_details['TRANSACTION'][0]) and fitter_id!=""):
The check `check_key("FITTER",transaction_details['TRANSACTION'][0])` is alredy performed on line 290

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
> +	if(check_key("FITTER",transaction_details['TRANSACTION'][0])==True):
Please give a few minutes to read the answer by Tim Goodman for [this question](https://softwareengineering.stackexchange.com/questions/12807/make-a-big-deal-out-of-true).

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
>  		details[employee_type]=str(employee_first_name)+" "+str(employee_last_name)+" ("+str(employee_short_name)+")"
Prefer using f-string instead of concatenation with the `+` operator

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
> +			fitter_name=str(fitter_first_name)+" "+str(fitter_last_name)+" ("+str(fitter_short_name)+")"
Prefer using f-string instead of concatenation with the `+` operator

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
> +			fitter_cmd="LIST FNAME LNAME SHORTNAME DATA {} EM TOJSON".format(fitter_id)
Prefer using f-string instead of formatting with the `format` method

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
>  	consultant_cmd="LIST FNAME LNAME SHORTNAME NICKNAME DATA {} EM TOJSON".format(phone_no)
Prefer using f-string instead of formatting with the `format` method

2020-05-29 02:00 UTC, KartikyaThakur commented on backend/uv-backend.py
>  	cmd="LIST PHONE.NO F.NAME L.NAME ADDRESS CITY ZIP.CODE PHONE.LONG PFID DATA {} CUSTOMERS TOJSON".format(customer_id)
Prefer using f-string instead of formatting with the `format` method

2020-06-01 02:48 UTC, ashishrawat0 commented on backend/unit-test.py
> +    def test_get_customerHistory(self):
Changed in latest commit

2020-06-03 01:02 UTC, KartikyaThakur approved these changes

2020-06-03 01:02 UTC, merged